ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'DBS';
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS dbs_config JSONB DEFAULT '{}'::jsonb;
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT true;
